// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Repository struct {
	ID           int64
	RepoOwner    string
	RepoName     string
	Description  pgtype.Text
	Forks        int32
	Stars        int32
	CreatedAt    pgtype.Timestamptz
	CommitsCount int32
}
