// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repositories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRepository = `-- name: GetRepository :one
SELECT
    id,
    repo_owner,
    repo_name,
    forks,
    stars,
    created_at
FROM
    repositories
WHERE
    repo_owner = $1
    AND repo_name = $2
`

type GetRepositoryParams struct {
	RepoOwner string
	RepoName  string
}

type GetRepositoryRow struct {
	ID        int64
	RepoOwner string
	RepoName  string
	Forks     int32
	Stars     int32
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetRepository(ctx context.Context, arg GetRepositoryParams) (GetRepositoryRow, error) {
	row := q.db.QueryRow(ctx, getRepository, arg.RepoOwner, arg.RepoName)
	var i GetRepositoryRow
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.Forks,
		&i.Stars,
		&i.CreatedAt,
	)
	return i, err
}

const upsertRepository = `-- name: UpsertRepository :one
INSERT INTO
    repositories (
        repo_owner,
        repo_name,
        description,
        forks,
        stars,
        created_at,
        commits_count
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7) ON CONFLICT (repo_owner, repo_name)
DO
UPDATE
SET
    forks = EXCLUDED.forks,
    stars = EXCLUDED.stars,
    created_at = EXCLUDED.created_at
RETURNING
    id,
    repo_owner,
    repo_name,
    forks,
    stars,
    created_at
`

type UpsertRepositoryParams struct {
	RepoOwner    string
	RepoName     string
	Description  pgtype.Text
	Forks        int32
	Stars        int32
	CreatedAt    pgtype.Timestamptz
	CommitsCount int32
}

type UpsertRepositoryRow struct {
	ID        int64
	RepoOwner string
	RepoName  string
	Forks     int32
	Stars     int32
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) (UpsertRepositoryRow, error) {
	row := q.db.QueryRow(ctx, upsertRepository,
		arg.RepoOwner,
		arg.RepoName,
		arg.Description,
		arg.Forks,
		arg.Stars,
		arg.CreatedAt,
		arg.CommitsCount,
	)
	var i UpsertRepositoryRow
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.Forks,
		&i.Stars,
		&i.CreatedAt,
	)
	return i, err
}
