version: "2"

linters:
  enable:
    - staticcheck
    - errcheck

  settings:
    staticcheck:
      checks: ["all", "-ST1000"]
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Printf
        - fmt.Println
