// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Subscription struct {
	ID        int64
	RepoOwner string
	RepoName  string
	CreatedAt pgtype.Timestamptz
}
