// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package sqlc

import (
	"context"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    repo_owner,
    repo_name
) VALUES (
    $1,
    $2
)
RETURNING id, repo_owner, repo_name, created_at
`

type CreateSubscriptionParams struct {
	RepoOwner string
	RepoName  string
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.RepoOwner, arg.RepoName)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :execrows
DELETE FROM subscriptions
WHERE repo_owner = $1 AND repo_name = $2
`

type DeleteSubscriptionParams struct {
	RepoOwner string
	RepoName  string
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSubscription, arg.RepoOwner, arg.RepoName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, repo_owner, repo_name, created_at
FROM subscriptions
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.RepoOwner,
			&i.RepoName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
