// Package docs Code generated by swaggo/swag-style setup for local project wiring.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/ping": {
            "get": {
                "summary": "Ping services",
                "produces": ["application/json"],
                "tags": ["health"],
                "responses": {
                    "200": { "description": "OK", "schema": { "$ref": "#/definitions/dto.PingResponse" } },
                    "503": { "description": "Service Unavailable", "schema": { "$ref": "#/definitions/dto.PingResponse" } }
                }
            }
        },
        "/api/repositories/info": {
            "get": {
                "summary": "Get repository information",
                "produces": ["application/json"],
                "tags": ["repositories"],
                "parameters": [
                    {
                        "type": "string",
                        "description": "GitHub repository URL",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": { "description": "OK", "schema": { "$ref": "#/definitions/dto.RepositoryInfoResponse" } },
                    "400": { "description": "Bad Request", "schema": { "$ref": "#/definitions/dto.ErrorResponse" } },
                    "401": { "description": "Unauthorized", "schema": { "$ref": "#/definitions/dto.ErrorResponse" } },
                    "404": { "description": "Not Found", "schema": { "$ref": "#/definitions/dto.ErrorResponse" } },
                    "429": { "description": "Too Many Requests", "schema": { "$ref": "#/definitions/dto.ErrorResponse" } },
                    "500": { "description": "Internal Server Error", "schema": { "$ref": "#/definitions/dto.ErrorResponse" } }
                }
            }
        }
    },
    "definitions": {
        "dto.PingServiceInfo": {
            "type": "object",
            "properties": {
                "name": { "type": "string" },
                "status": { "type": "string" }
            }
        },
        "dto.PingResponse": {
            "type": "object",
            "properties": {
                "status": { "type": "string" },
                "services": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/dto.PingServiceInfo" }
                }
            }
        },
        "dto.RepositoryInfoResponse": {
            "type": "object",
            "properties": {
                "name": { "type": "string" },
                "owner": { "type": "string" },
                "description": { "type": "string" },
                "forks": { "type": "integer" },
                "stars": { "type": "integer" },
                "created_at": { "type": "string" },
                "commits_count": { "type": "integer" }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": { "type": "string" }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Repo Stat API",
	Description:      "API Gateway for repository info and service health checks.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
