app:
  app_name: "repo-stat-collector"

services:
  subscriber: "localhost:8081"

logger:
  log_level: "DEBUG"

kafka:
  brokers:
    - "kafka:9092"
  request_topic: "collect-requests"
  result_topic: "collect-results"
  group_id: "collector-group"
